import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { useAuth } from '../contexts/AuthContext'
import { usePeriod } from '../contexts/PeriodContext'
import { totalIncomeForPeriod } from '../services/incomes'
import { totalExpensesForPeriod, expensesByCategory, getExpensedCategoryIds, createExpense } from '../services/expenses'
import { listCategories } from '../services/categories'
import { totalSavingsForPeriod, listGoalsWithBalances } from '../services/savings'
import { getNetWorthForPeriod, getNetWorthHistory } from '../services/networth'
import { getAccountBalancesForPeriod } from '../services/accounts'
import { autoGenerateRecurringExpenses } from '../services/recurring'
import { getLatestRatesToDOP } from '../services/exchangeRates'
import { percentChange, savingsRate, convertToDOP } from '../utils/finance'
import { FinancialHero } from '../components/dashboard/FinancialHero'
import { KpiGrid } from '../components/dashboard/KpiGrid'
import { GoalRing } from '../components/dashboard/GoalRing'
import { Card, CardHeader } from '../components/ui/Card'
import { CategoryDonut } from '../components/charts/CategoryDonut'
import { Skeleton, EmptyState } from '../components/ui/Feedback'
import { Button } from '../components/ui/Button'
import { Input } from '../components/ui/Input'
import { formatMoney } from '../utils/format'
import { PiggyBank, Repeat, CalendarClock, Check, X } from 'lucide-react'

export default function Dashboard() {
  const { user } = useAuth()
  const { currentPeriod, allPeriods } = usePeriod()
  const [loading, setLoading] = useState(true)
  const [data, setData] = useState(null)
  const [autoGeneratedRecurring, setAutoGeneratedRecurring] = useState([])
  const [autoBannerDismissed, setAutoBannerDismissed] = useState(false)
  const [upcomingPayments, setUpcomingPayments] = useState([])
  const [payingCategoryId, setPayingCategoryId] = useState(null)
  const [payAmount, setPayAmount] = useState('')

  const load = async () => {
    // best-effort en el cliente: genera automáticamente (sin pedir
    // confirmación) los gastos recurrentes cuyo día ya llegó este período,
    // antes de calcular los totales — así ya quedan reflejados abajo
    const created = await autoGenerateRecurringExpenses(user.id, currentPeriod).catch(() => [])
    setAutoGeneratedRecurring(created)
    if (created.length > 0) setAutoBannerDismissed(false)

    const [income, expenses, savings, netWorth, goals, categoryBreakdown, balances, ratesToDOP] = await Promise.all([
      totalIncomeForPeriod(user.id, currentPeriod.id),
      totalExpensesForPeriod(user.id, currentPeriod.id),
      totalSavingsForPeriod(user.id, currentPeriod.id),
      getNetWorthForPeriod(user.id, currentPeriod.id),
      listGoalsWithBalances(user.id),
      expensesByCategory(user.id, currentPeriod.id),
      getAccountBalancesForPeriod(user.id, currentPeriod.id),
      getLatestRatesToDOP(user.id),
    ])
    // próximos pagos: categorías con fecha límite que aún no se han pagado este período
    const [allCategories, expensedCategoryIds] = await Promise.all([
      listCategories(user.id),
      getExpensedCategoryIds(user.id, currentPeriod.id),
    ])
    const upcoming = allCategories
      .filter((c) => c.due_day && !expensedCategoryIds.has(c.id))
      .sort((a, b) => a.due_day - b.due_day)
    setUpcomingPayments(upcoming)

    // patrimonio del período anterior para calcular % de crecimiento
    const history = await getNetWorthHistory(user.id)
    const idx = history.findIndex((h) => h.period_id === currentPeriod.id)
    const previousNetWorth = idx > 0 ? history[idx - 1].net_worth : null

    setData({
      income,
      expenses,
      savings,
      netWorth: Number(netWorth.net_worth ?? 0),
      growthPct: previousNetWorth ? percentChange(netWorth.net_worth, previousNetWorth) : 0,
      goals,
      categoryBreakdown,
      // convierte cada cuenta a DOP con la tasa más reciente antes de sumar
      available: balances.reduce((s, b) => {
        const converted = convertToDOP(b.balance, b.accounts?.currency, ratesToDOP)
        return converted === null ? s : s + converted
      }, 0),
    })
    setLoading(false)
  }

  useEffect(() => {
    if (!user || !currentPeriod) return
    let active = true
    setLoading(true)
    load().catch(() => { if (active) setLoading(false) })
    return () => { active = false }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user, currentPeriod])

  const handleMarkPaid = async (category) => {
    if (!payAmount) return
    const daysInMonth = new Date(currentPeriod.year, currentPeriod.month, 0).getDate()
    const day = Math.min(category.due_day, daysInMonth)
    const expenseDate = `${currentPeriod.year}-${String(currentPeriod.month).padStart(2, '0')}-${String(day).padStart(2, '0')}`
    await createExpense(user.id, currentPeriod.id, {
      categoryId: category.id,
      amount: Number(payAmount),
      description: `${category.name} (pago)`,
      expenseDate,
    })
    setPayingCategoryId(null)
    setPayAmount('')
    load()
  }

  // solo la primera carga muestra el skeleton — cambiar de mes actualiza los
  // datos en el sitio en vez de desmontar todo el panel (evita el "salto")
  if (!data) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-40 w-full" />
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
          {Array.from({ length: 6 }).map((_, i) => <Skeleton key={i} className="h-20" />)}
        </div>
      </div>
    )
  }

  // Tasa de Ahorro = % del ingreso que realmente se destinó a metas de ahorro
  // (antes se calculaba como (ingreso - gastos) / ingreso, que en realidad
  // mide "ingreso no gastado" — no es lo mismo que "ingreso ahorrado" si
  // queda dinero sin asignar a ningún lado)
  const rate = savingsRate(data.income, data.savings)
  // suma de lo ya gastado + lo ya aportado a metas este período (no lo que
  // "falta mover" a futuro, a pesar del nombre — por eso el label es explícito)
  const spentAndSaved = data.expenses + data.savings
  const remaining = data.income - spentAndSaved

  const kpis = [
    {
      label: 'Gastado + Ahorrado',
      value: spentAndSaved,
      tooltip: 'Gastos + aportes a metas de ahorro de este período. Todo el dinero que ya salió de tu ingreso, sea a gastos o a ahorro.',
    },
    {
      label: 'Restante',
      value: remaining,
      tooltip: 'Ingresos − Gastos − Ahorros de este período. Es la parte de tu ingreso que aún no has gastado ni ahorrado.',
    },
    {
      label: 'Tasa de Ahorro',
      value: rate,
      isPercent: true,
      tooltip: 'Aportes a metas de ahorro como % de tus ingresos de este período. Entre más alto, mayor proporción de lo que ganas estás ahorrando.',
    },
  ]

  return (
    <motion.div
      className="space-y-6"
      animate={{ opacity: loading ? 0.6 : 1 }}
      transition={{ type: 'spring', bounce: 0, duration: 0.3 }}
    >
      {autoGeneratedRecurring.length > 0 && !autoBannerDismissed && (
        <div className="flex items-center justify-between gap-4 bg-info/10 border border-info/30 rounded-xl2 px-5 py-4">
          <div className="flex items-center gap-3">
            <Repeat size={18} className="text-info shrink-0" />
            <p className="text-sm text-ink">
              Se registraron automáticamente {autoGeneratedRecurring.length} gasto{autoGeneratedRecurring.length === 1 ? '' : 's'} recurrente{autoGeneratedRecurring.length === 1 ? '' : 's'} de este mes: {autoGeneratedRecurring.map((e) => e.description || e.categoryName).join(', ')}.
            </p>
          </div>
          <button onClick={() => setAutoBannerDismissed(true)} className="text-ink-faint hover:text-ink transition-colors shrink-0" aria-label="Cerrar aviso">
            <X size={16} />
          </button>
        </div>
      )}

      <FinancialHero
        netWorth={data.netWorth}
        growthPct={data.growthPct}
        income={data.income}
        expenses={data.expenses}
        savings={data.savings}
        available={data.available}
      />

      <KpiGrid kpis={kpis} />

      {upcomingPayments.length > 0 && (
        <Card>
          <CardHeader title="Próximos pagos" subtitle="Categorías con fecha límite sin pagar este mes" icon={CalendarClock} />
          <ul className="divide-y divide-border">
            {upcomingPayments.map((c) => (
              <li key={c.id} className="py-2.5">
                <div className="flex items-center justify-between gap-3">
                  <div className="flex items-center gap-2">
                    <CalendarClock size={14} className="text-ink-faint" />
                    <span className="text-sm font-medium text-ink">{c.name}</span>
                    <span className="text-xs text-ink-faint">vence el día {c.due_day}</span>
                  </div>
                  {payingCategoryId === c.id ? (
                    <div className="flex items-center gap-2">
                      <Input
                        type="number"
                        step="0.01"
                        autoFocus
                        placeholder="Monto"
                        value={payAmount}
                        onChange={(e) => setPayAmount(e.target.value)}
                        className="max-w-[110px] tabular"
                      />
                      <button onClick={() => handleMarkPaid(c)} className="text-emerald-500 hover:text-emerald-400 transition-colors">
                        <Check size={16} />
                      </button>
                    </div>
                  ) : (
                    <Button variant="secondary" onClick={() => { setPayingCategoryId(c.id); setPayAmount('') }} className="shrink-0">
                      Marcar como pagado
                    </Button>
                  )}
                </div>
              </li>
            ))}
          </ul>
        </Card>
      )}

      <div className="grid md:grid-cols-2 gap-4">
        <Card>
          <CardHeader title="Gastos por categoría" subtitle="Mes actual" />
          <CategoryDonut data={data.categoryBreakdown} />
        </Card>

        <Card>
          <CardHeader title="Metas de ahorro" subtitle="Progreso acumulado" />
          {data.goals.length === 0 ? (
            <EmptyState icon={PiggyBank} title="Sin metas aún" description="Crea una meta en Ajustes para empezar a rastrear tu progreso." />
          ) : (
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 py-2">
              {data.goals.map((goal) => (
                <GoalRing
                  key={goal.id}
                  label={goal.name}
                  current={goal.balance}
                  target={goal.target_amount || goal.balance || 1}
                />
              ))}
            </div>
          )}
        </Card>
      </div>
    </motion.div>
  )
}
