import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { useAuth } from '../contexts/AuthContext'
import { usePeriod } from '../contexts/PeriodContext'
import { totalIncomeForPeriod } from '../services/incomes'
import { totalExpensesForPeriod, expensesByCategory, getExpensedCategoryIds, createExpense, getRecentCategoryAverage } from '../services/expenses'
import { listCategories } from '../services/categories'
import { totalSavingsForPeriod, listGoalsWithBalances } from '../services/savings'
import { getNetWorthForPeriod, getNetWorthHistory } from '../services/networth'
import { getAccountBalancesForPeriod } from '../services/accounts'
import { autoGenerateRecurringExpenses } from '../services/recurring'
import { autoGeneratePayrollIncome } from '../services/payroll'
import { getLatestRatesToDOP } from '../services/exchangeRates'
import { getBudgetUsageForPeriod } from '../services/categories'
import { getCreditCardUsageForPeriod } from '../services/networth'
import { buildMonthlyOverview, lastNPeriods } from '../services/analytics'
import { percentChange, absoluteChange, savingsRate, convertToDOP, computeFinancialHealthScore, emergencyFundStatus } from '../utils/finance'
import { InfoTooltip } from '../components/ui/InfoTooltip'
import { FinancialHero } from '../components/dashboard/FinancialHero'
import { KpiGrid } from '../components/dashboard/KpiGrid'
import { GoalRing } from '../components/dashboard/GoalRing'
import { Card, CardHeader } from '../components/ui/Card'
import { CategoryDonut } from '../components/charts/CategoryDonut'
import { Skeleton, EmptyState } from '../components/ui/Feedback'
import { Button } from '../components/ui/Button'
import { Input } from '../components/ui/Input'
import { formatMoney, formatPercent } from '../utils/format'
import { PiggyBank, Repeat, CalendarClock, Check, X, TrendingUp, TrendingDown } from 'lucide-react'

// % de aumento vs el promedio de los últimos 3 meses para disparar una alerta
const CATEGORY_ALERT_THRESHOLD = 0.2

const HEALTH_LABEL_CLASS = {
  Excelente: 'bg-emerald-500/10 text-emerald-500',
  Buena: 'bg-info/10 text-info',
  Regular: 'bg-warn/10 text-warn',
  'En riesgo': 'bg-alert/10 text-alert',
}

export default function Dashboard() {
  const { user } = useAuth()
  const { currentPeriod, allPeriods } = usePeriod()
  const [loading, setLoading] = useState(true)
  const [data, setData] = useState(null)
  const [autoGeneratedRecurring, setAutoGeneratedRecurring] = useState([])
  const [autoBannerDismissed, setAutoBannerDismissed] = useState(false)
  const [upcomingPayments, setUpcomingPayments] = useState([])
  const [payingCategoryId, setPayingCategoryId] = useState(null)
  const [payAmount, setPayAmount] = useState('')

  const load = async () => {
    // best-effort en el cliente: genera automáticamente (sin pedir
    // confirmación) los gastos recurrentes cuyo día ya llegó este período,
    // antes de calcular los totales — así ya quedan reflejados abajo
    const created = await autoGenerateRecurringExpenses(user.id, currentPeriod).catch(() => [])
    // mismo mecanismo best-effort para el ingreso de nómina, si hay uno configurado
    const payrollIncome = await autoGeneratePayrollIncome(user.id, currentPeriod).catch(() => null)
    setAutoGeneratedRecurring(payrollIncome ? [...created, { ...payrollIncome, categoryName: payrollIncome.source }] : created)
    if (created.length > 0 || payrollIncome) setAutoBannerDismissed(false)

    const [income, expenses, savings, netWorth, goals, categoryBreakdown, balances, ratesToDOP] = await Promise.all([
      totalIncomeForPeriod(user.id, currentPeriod.id),
      totalExpensesForPeriod(user.id, currentPeriod.id),
      totalSavingsForPeriod(user.id, currentPeriod.id),
      getNetWorthForPeriod(user.id, currentPeriod.id),
      listGoalsWithBalances(user.id),
      expensesByCategory(user.id, currentPeriod.id),
      getAccountBalancesForPeriod(user.id, currentPeriod.id),
      getLatestRatesToDOP(user.id),
    ])
    // próximos pagos: categorías con fecha límite que aún no se han pagado este período
    const [allCategories, expensedCategoryIds] = await Promise.all([
      listCategories(user.id),
      getExpensedCategoryIds(user.id, currentPeriod.id),
    ])
    const upcoming = allCategories
      .filter((c) => c.due_day && !expensedCategoryIds.has(c.id))
      .sort((a, b) => a.due_day - b.due_day)
    setUpcomingPayments(upcoming)

    // patrimonio del período anterior para calcular % de crecimiento
    const history = await getNetWorthHistory(user.id)
    const idx = history.findIndex((h) => h.period_id === currentPeriod.id)
    const previousNetWorth = idx > 0 ? history[idx - 1].net_worth : null

    // alertas: categorías cuyo gasto este mes supera en más de CATEGORY_ALERT_THRESHOLD
    // su promedio de los últimos 3 períodos anteriores (solo informa, nunca bloquea)
    const currentIdx = allPeriods.findIndex((p) => p.id === currentPeriod.id)
    const priorPeriods = currentIdx > 0 ? allPeriods.slice(Math.max(0, currentIdx - 3), currentIdx) : []
    let categoryAlerts = []
    if (priorPeriods.length > 0) {
      const alerts = await Promise.all(
        categoryBreakdown.filter((c) => c.total > 0).map(async (c) => {
          const avg = await getRecentCategoryAverage(user.id, c.id, priorPeriods)
          if (avg > 0 && c.total > avg * (1 + CATEGORY_ALERT_THRESHOLD)) {
            return { name: c.name, total: c.total, avg, pctChange: ((c.total - avg) / avg) * 100 }
          }
          return null
        })
      )
      categoryAlerts = alerts.filter(Boolean).sort((a, b) => b.pctChange - a.pctChange)
    }

    // promedios de 3/6/12 meses + comparación vs el mes inmediatamente
    // anterior (no el mes anterior "seleccionado" — eso ya existe en
    // History.jsx como comparación manual entre dos períodos cualquiera)
    const last12 = lastNPeriods(allPeriods.slice(0, currentIdx + 1), 12)
    const monthlyOverview = await buildMonthlyOverview(user.id, last12)
    const avgOf = (n, key) => {
      const slice = monthlyOverview.slice(-n)
      return slice.length === 0 ? 0 : slice.reduce((s, m) => s + m[key], 0) / slice.length
    }
    const averages = {
      expenses: { m3: avgOf(3, 'expenses'), m6: avgOf(6, 'expenses'), m12: avgOf(12, 'expenses') },
      savings: { m3: avgOf(3, 'savings'), m6: avgOf(6, 'savings'), m12: avgOf(12, 'savings') },
    }
    const prevMonth = monthlyOverview.length >= 2 ? monthlyOverview[monthlyOverview.length - 2] : null
    const currentRate = savingsRate(income, savings)
    const monthComparison = prevMonth ? {
      income: { pct: percentChange(income, prevMonth.income), diff: absoluteChange(income, prevMonth.income) },
      expenses: { pct: percentChange(expenses, prevMonth.expenses), diff: absoluteChange(expenses, prevMonth.expenses) },
      savings: { pct: percentChange(savings, prevMonth.savings), diff: absoluteChange(savings, prevMonth.savings) },
      savingsRate: { pct: percentChange(currentRate, savingsRate(prevMonth.income, prevMonth.savings)), diff: currentRate - savingsRate(prevMonth.income, prevMonth.savings) },
    } : null

    // Índice de Salud Financiera — ver utils/finance.js para la fórmula exacta
    const [budgetUsage, cardUsage] = await Promise.all([
      getBudgetUsageForPeriod(user.id, currentPeriod.id),
      getCreditCardUsageForPeriod(user.id, currentPeriod.id),
    ])
    const emergencyGoal = goals.find((g) => g.is_emergency_fund)
    const avgMonthlyExpenses = averages.expenses.m3
    const emergencyFundMonths = emergencyGoal && avgMonthlyExpenses > 0
      ? emergencyGoal.balance / avgMonthlyExpenses
      : null
    const budgetAdherencePct = budgetUsage.length > 0
      ? (budgetUsage.filter((b) => b.pct <= 100).length / budgetUsage.length) * 100
      : null
    const creditUtilizationPct = cardUsage.length > 0
      ? cardUsage.reduce((s, c) => {
          const limit = Number(c.credit_cards?.credit_limit) || 0
          return s + (limit > 0 ? (Number(c.balance) / limit) * 100 : 0)
        }, 0) / cardUsage.length
      : null
    const healthScore = computeFinancialHealthScore({ emergencyFundMonths, savingsRatePct: currentRate, budgetAdherencePct, creditUtilizationPct })

    setData({
      income,
      expenses,
      savings,
      netWorth: Number(netWorth.net_worth ?? 0),
      growthPct: previousNetWorth ? percentChange(netWorth.net_worth, previousNetWorth) : 0,
      goals,
      categoryBreakdown,
      categoryAlerts,
      averages,
      monthComparison,
      healthScore,
      emergencyFundMonths,
      // convierte cada cuenta a DOP con la tasa más reciente antes de sumar
      available: balances.reduce((s, b) => {
        const converted = convertToDOP(b.balance, b.accounts?.currency, ratesToDOP)
        return converted === null ? s : s + converted
      }, 0),
    })
    setLoading(false)
  }

  useEffect(() => {
    if (!user || !currentPeriod) return
    let active = true
    setLoading(true)
    load().catch(() => { if (active) setLoading(false) })
    return () => { active = false }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [user, currentPeriod])

  const handleMarkPaid = async (category) => {
    if (!payAmount) return
    const daysInMonth = new Date(currentPeriod.year, currentPeriod.month, 0).getDate()
    const day = Math.min(category.due_day, daysInMonth)
    const expenseDate = `${currentPeriod.year}-${String(currentPeriod.month).padStart(2, '0')}-${String(day).padStart(2, '0')}`
    await createExpense(user.id, currentPeriod.id, {
      categoryId: category.id,
      amount: Number(payAmount),
      description: `${category.name} (pago)`,
      expenseDate,
    })
    setPayingCategoryId(null)
    setPayAmount('')
    load()
  }

  // solo la primera carga muestra el skeleton — cambiar de mes actualiza los
  // datos en el sitio en vez de desmontar todo el panel (evita el "salto")
  if (!data) {
    return (
      <div className="space-y-4">
        <Skeleton className="h-40 w-full" />
        <div className="grid grid-cols-2 md:grid-cols-3 gap-3">
          {Array.from({ length: 6 }).map((_, i) => <Skeleton key={i} className="h-20" />)}
        </div>
      </div>
    )
  }

  // Tasa de Ahorro = % del ingreso que realmente se destinó a metas de ahorro
  // (antes se calculaba como (ingreso - gastos) / ingreso, que en realidad
  // mide "ingreso no gastado" — no es lo mismo que "ingreso ahorrado" si
  // queda dinero sin asignar a ningún lado)
  const rate = savingsRate(data.income, data.savings)
  // suma de lo ya gastado + lo ya aportado a metas este período (no lo que
  // "falta mover" a futuro, a pesar del nombre — por eso el label es explícito)
  const spentAndSaved = data.expenses + data.savings
  const remaining = data.income - spentAndSaved

  const kpis = [
    {
      label: 'Gastado + Ahorrado',
      value: spentAndSaved,
      tooltip: 'Gastos + aportes a metas de ahorro de este período. Todo el dinero que ya salió de tu ingreso, sea a gastos o a ahorro.',
    },
    {
      label: 'Restante',
      value: remaining,
      tooltip: 'Ingresos − Gastos − Ahorros de este período. Es la parte de tu ingreso que aún no has gastado ni ahorrado.',
    },
    {
      label: 'Porcentaje de Ahorro',
      value: rate,
      isPercent: true,
      tooltip: 'Aportes a metas de ahorro como % de tus ingresos de este período. Entre más alto, mayor proporción de lo que ganas estás ahorrando.',
    },
  ]

  return (
    <motion.div
      className="space-y-6"
      animate={{ opacity: loading ? 0.6 : 1 }}
      transition={{ type: 'spring', bounce: 0, duration: 0.3 }}
    >
      {autoGeneratedRecurring.length > 0 && !autoBannerDismissed && (
        <div className="flex items-center justify-between gap-4 bg-info/10 border border-info/30 rounded-xl2 px-5 py-4">
          <div className="flex items-center gap-3">
            <Repeat size={18} className="text-info shrink-0" />
            <p className="text-sm text-ink">
              Se registraron automáticamente {autoGeneratedRecurring.length} movimiento{autoGeneratedRecurring.length === 1 ? '' : 's'} recurrente{autoGeneratedRecurring.length === 1 ? '' : 's'} de este mes: {autoGeneratedRecurring.map((e) => e.description || e.categoryName).join(', ')}.
            </p>
          </div>
          <button onClick={() => setAutoBannerDismissed(true)} className="text-ink-faint hover:text-ink transition-colors shrink-0" aria-label="Cerrar aviso">
            <X size={16} />
          </button>
        </div>
      )}

      <FinancialHero
        netWorth={data.netWorth}
        growthPct={data.growthPct}
        income={data.income}
        expenses={data.expenses}
        savings={data.savings}
        available={data.available}
      />

      <KpiGrid kpis={kpis} />

      {data.categoryAlerts.length > 0 && (
        <Card>
          <CardHeader title="Alertas de gasto" subtitle="Categorías por encima de su promedio reciente — solo informativo" icon={TrendingUp} />
          <ul className="divide-y divide-border">
            {data.categoryAlerts.map((a) => (
              <li key={a.name} className="py-2.5 text-sm text-ink">
                Tus gastos en <span className="font-medium">{a.name}</span> aumentaron{' '}
                <span className="font-medium text-alert">{formatPercent(a.pctChange, 0)}</span> respecto al promedio de
                los últimos 3 meses ({formatMoney(a.total)} vs. {formatMoney(a.avg)} promedio).
              </li>
            ))}
          </ul>
        </Card>
      )}

      {data.healthScore && (
        <Card>
          <CardHeader
            title={
              <span className="flex items-center gap-1.5">
                Salud Financiera
                <InfoTooltip text="Promedio de las métricas disponibles: fondo de emergencia (meses de gasto cubiertos, 6+ = 100pts), porcentaje de ahorro, % de categorías dentro de presupuesto, y uso de tarjetas de crédito (menos uso = mejor). Es un criterio propio de la app, no un estándar oficial — cada componente se muestra abajo." />
              </span>
            }
          />
          <div className="flex items-center gap-4 mb-4">
            <span className="font-display font-semibold text-3xl text-ink tabular">{data.healthScore.score}</span>
            <span className={`text-xs font-medium px-2.5 py-1 rounded-full ${HEALTH_LABEL_CLASS[data.healthScore.label]}`}>
              {data.healthScore.label}
            </span>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {data.healthScore.components.map((c) => (
              <div key={c.key}>
                <p className="text-ink-faint text-xs mb-1">{c.label}</p>
                <p className="tabular text-sm font-medium text-ink">{formatPercent(c.score, 0)}</p>
              </div>
            ))}
          </div>
          {data.emergencyFundMonths != null && (
            <p className="text-xs text-ink-faint mt-3 pt-3 border-t border-border">
              Fondo de emergencia: {data.emergencyFundMonths.toFixed(1)} meses de gasto cubiertos ({emergencyFundStatus(data.emergencyFundMonths) === 'en_riesgo' ? 'en riesgo, menos de 3 meses' : emergencyFundStatus(data.emergencyFundMonths) === 'adecuado' ? 'adecuado, 3-6 meses' : 'sólido, más de 6 meses'}).
            </p>
          )}
        </Card>
      )}

      <Card>
        <CardHeader title="Promedios y comparación" subtitle="Este mes vs el mes anterior, y promedios recientes" />
        {data.monthComparison ? (
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-5">
            <MonthComparisonStat label="Ingresos" value={data.income} change={data.monthComparison.income} />
            <MonthComparisonStat label="Gastos" value={data.expenses} change={data.monthComparison.expenses} invert />
            <MonthComparisonStat label="Ahorro" value={data.savings} change={data.monthComparison.savings} />
            <MonthComparisonStat label="Porcentaje de Ahorro" value={savingsRate(data.income, data.savings)} change={data.monthComparison.savingsRate} isPercent />
          </div>
        ) : (
          <p className="text-xs text-ink-faint mb-5">Aún no hay un mes anterior con el que comparar.</p>
        )}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 sm:gap-4 pt-4 border-t border-border">
          <div>
            <p className="text-ink-faint text-xs mb-2">Gasto promedio mensual</p>
            <div className="grid grid-cols-3 gap-2">
              <AverageStat label="3m" value={data.averages.expenses.m3} />
              <AverageStat label="6m" value={data.averages.expenses.m6} />
              <AverageStat label="12m" value={data.averages.expenses.m12} />
            </div>
          </div>
          <div>
            <p className="text-ink-faint text-xs mb-2">Ahorro promedio mensual</p>
            <div className="grid grid-cols-3 gap-2">
              <AverageStat label="3m" value={data.averages.savings.m3} />
              <AverageStat label="6m" value={data.averages.savings.m6} />
              <AverageStat label="12m" value={data.averages.savings.m12} />
            </div>
          </div>
        </div>
      </Card>

      {upcomingPayments.length > 0 && (
        <Card>
          <CardHeader title="Próximos pagos" subtitle="Categorías con fecha límite sin pagar este mes" icon={CalendarClock} />
          <ul className="divide-y divide-border">
            {upcomingPayments.map((c) => (
              <li key={c.id} className="py-2.5">
                <div className="flex items-center justify-between gap-3">
                  <div className="flex items-center gap-2">
                    <CalendarClock size={14} className="text-ink-faint" />
                    <span className="text-sm font-medium text-ink">{c.name}</span>
                    <span className="text-xs text-ink-faint">vence el día {c.due_day}</span>
                  </div>
                  {payingCategoryId === c.id ? (
                    <div className="flex items-center gap-2">
                      <Input
                        type="number"
                        step="0.01"
                        autoFocus
                        placeholder="Monto"
                        value={payAmount}
                        onChange={(e) => setPayAmount(e.target.value)}
                        className="max-w-[110px] tabular"
                      />
                      <button onClick={() => handleMarkPaid(c)} className="text-emerald-500 hover:text-emerald-400 transition-colors">
                        <Check size={16} />
                      </button>
                    </div>
                  ) : (
                    <Button variant="secondary" onClick={() => { setPayingCategoryId(c.id); setPayAmount('') }} className="shrink-0">
                      Marcar como pagado
                    </Button>
                  )}
                </div>
              </li>
            ))}
          </ul>
        </Card>
      )}

      <div className="grid md:grid-cols-2 gap-4">
        <Card>
          <CardHeader title="Gastos por categoría" subtitle="Mes actual" />
          <CategoryDonut data={data.categoryBreakdown} />
        </Card>

        <Card>
          <CardHeader title="Metas de ahorro" subtitle="Progreso acumulado" />
          {data.goals.length === 0 ? (
            <EmptyState
              icon={PiggyBank}
              title="Sin metas aún"
              description="Crea una meta de ahorro para empezar a rastrear tu progreso."
              action={<Link to="/savings"><Button variant="secondary">Ir a Ahorros</Button></Link>}
            />
          ) : (
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 py-2">
              {data.goals.map((goal) => (
                <GoalRing
                  key={goal.id}
                  label={goal.name}
                  current={goal.balance}
                  target={goal.target_amount || goal.balance || 1}
                />
              ))}
            </div>
          )}
        </Card>
      </div>

      {data.categoryBreakdown.length > 0 && (
        <Card>
          <CardHeader title="Top de gastos" subtitle="Categorías de este mes, de mayor a menor" />
          <ul className="space-y-3">
            {[...data.categoryBreakdown]
              .sort((a, b) => b.total - a.total)
              .map((c) => {
                const pct = data.expenses > 0 ? (c.total / data.expenses) * 100 : 0
                return (
                  <li key={c.id}>
                    <div className="flex items-center justify-between text-sm mb-1">
                      <span className="text-ink">{c.name}</span>
                      <span className="tabular text-ink-muted">
                        {formatMoney(c.total)} <span className="text-ink-faint">({formatPercent(pct, 0)})</span>
                      </span>
                    </div>
                    <div className="h-1.5 rounded-full bg-surface-sunken overflow-hidden">
                      <div className="h-full rounded-full bg-emerald-500" style={{ width: `${Math.min(pct, 100)}%` }} />
                    </div>
                  </li>
                )
              })}
          </ul>
        </Card>
      )}
    </motion.div>
  )
}

function MonthComparisonStat({ label, value, change, invert = false, isPercent = false }) {
  const isGood = invert ? change.pct <= 0 : change.pct >= 0
  return (
    <div>
      <p className="text-ink-faint text-xs mb-1">{label}</p>
      <p className="tabular font-display font-semibold text-ink">{isPercent ? formatPercent(value) : formatMoney(value)}</p>
      <div className={`flex items-center gap-1 text-xs mt-0.5 ${isGood ? 'text-emerald-500' : 'text-alert'}`}>
        {isGood ? <TrendingUp size={12} /> : <TrendingDown size={12} />}
        <span className="tabular">{formatPercent(Math.abs(change.pct))}</span>
        <span className="text-ink-faint">vs. mes anterior</span>
      </div>
    </div>
  )
}

function AverageStat({ label, value }) {
  return (
    <div>
      <p className="text-[10px] text-ink-faint">{label}</p>
      <p className="tabular text-sm font-medium text-ink">{formatMoney(value)}</p>
    </div>
  )
}
